name: Scheduled Weather Data Ingestion

# Configure the workflow to run on a schedule and manually
on:
  schedule:
    # This cron job runs once every 24 hours at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      city:
        description: 'City to fetch weather data for'
        required: true
        default: 'Toronto'

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker container
        run: docker build -t weather-ingest .

      - name: Run Docker container
        run: docker run --env WEATHER_API_KEY="${{ secrets.WEATHER_API_KEY }}" --env CITY="${{ github.event.inputs.city }}" --volume ${{ github.workspace }}:/app weather-ingest

      - name: Commit and push weather_data.json
        # This step is conditional, only running on the schedule or on manual trigger.
        # I.e. future actions defined in the 'on' section won't trigger this step.
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add weather_data.json
          git commit -m "chore: Update weather data via scheduled ingestion"
          git push

